name: Peter Schnelle
favicon: null
layout_spectrum: 0.8647819093894213
typography_spectrum: 0.02220839075744152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5316597139462829
  lightness: 0.5966241410933435
  saturation: 0.18056678283028305
  rhythmicContrast: 0.6113888819236308
purpose: []
