name: Peter Schnelle
favicon: null
layout_spectrum: 0.24512
typography_spectrum: 0.79199
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020307'
    - '#6fbaf3'
    - '#3c75c6'
    - '#ffffff'
    - '#383e4a'
  brandStrength: 0.6875
  lightness: 0.5966241410933435
  saturation: 0.25
  rhythmicContrast: 0.6113888819236308
purpose: []
