name: Peter Schnelle
favicon: null
layout_spectrum: 0.24512
typography_spectrum: 0.79199
title: 'Technical sales guy, with a background in helping grow startup companies'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020307'
    - '#6fbaf3'
    - '#3c75c6'
    - '#ffffff'
    - '#383e4a'
  brandStrength: 0.9375
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
